"""Shared plumbing for the §5 tools: the error type and the provenance helpers.

Kept in a leaf module rather than in ``tools/__init__.py`` so the tool modules
can import it without the package importing them back.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from datetime import UTC, datetime
from typing import Any

import psycopg

from nightglass.schemas import Provenance

#: Copernicus data are free and open; the granules were staged from ASF.
SENTINEL_LICENCE = (
    "Contains modified Copernicus Sentinel data 2026, processed by ESA. "
    "Staged via the Alaska Satellite Facility."
)

#: The Danish Maritime Authority requires this line verbatim wherever its data
#: is used (§8). It travels on every Match rather than living in a README, so a
#: report generated by a machine cannot lose it.
DMA_ATTRIBUTION = (
    "Danish Maritime Authority — AIS data. The Danish Maritime Authority accepts "
    "no liability for any errors or omissions, nor for the correctness or "
    "completeness of the data."
)


class ToolError(RuntimeError):
    """A tool could not answer, and says what would make it able to.

    Every raise site carries a remediation hint. The FastAPI layer turns this
    into a 503 with the hint in the detail and the MCP layer returns it as the
    tool's error text, so the same sentence reaches an analyst at a terminal, an
    HTTP client, and a language model deciding what to do next. A tool that
    fails without saying what to run is a tool that gets retried blindly, and
    §M5 already measured what this model does when a tool result does not
    satisfy it: it calls the tool again with tweaked arguments, four times.
    """


def now() -> datetime:
    return datetime.now(UTC)


@contextmanager
def session(conn: psycopg.Connection | None = None) -> Iterator[psycopg.Connection]:
    """Yield a connection, opening one only if the caller did not supply it.

    §5 says the tools are pure functions over the database — no pool, no
    module-level connection, nothing held between calls. But `correlate` chains
    three of them, and opening three connections to answer one question is
    waste, so a caller may thread its own down. Ownership is unambiguous:
    whoever opened it closes it.
    """
    if conn is not None:
        yield conn
        return
    from nightglass.spatial.db import connect

    with connect() as owned:
        yield owned


def scene_provenance(row: dict[str, Any], *, note: str | None = None) -> Provenance:
    return Provenance(
        source="ESA Copernicus Sentinel-1 (via ASF)",
        retrieved_at=now(),
        source_url=_self_link(row.get("item")),
        licence=SENTINEL_LICENCE,
        note=note,
    )


def _self_link(item: Any) -> str | None:
    """The STAC Item's own `self` link, if the catalogue kept one."""
    if not isinstance(item, dict):
        return None
    for link in item.get("links") or []:
        if isinstance(link, dict) and link.get("rel") == "self" and link.get("href"):
            return str(link["href"])
    return None
